#!/bin/bash
# This is a bash script that check a GPIO input, and if it is to GND print an output.
# This script require a pull-down circuit.
# www.raspberrygaming.tk


gpio mode 14 in         # 14 is the GPIO number, you can change it.

state=`gpio read 14`


while true
do

  state=`gpio read 14`
  #echo $stato         # you can uncomment this if you want the output shown at video.

  if [ $state = 0 ]; then

         echo "something you want!"

         break

  fi

done
