#!/bin/bash
# This is a bash script thath check your Raspberry CPU temperature and if it reach a custom treashold it send you an email.
# You can set this to start every X minute with cronjob.


############ Parameters ############

user="pi"
tempmax="55"
sender="youremail@gmail.com"
receiver="youremailoranother@gmail.com"
smtp="smtp.gmail.com:587"
username="youremail"	# WITHOUT @gmail.com
pass="yourpassword"

#####################################


temp="`cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2`"

if [ "$temp" -ge "$tempmax" ]; then

 object="Raspberry Temperature Alarm!"

 tempresult="Watch! Raspberry has reached the temperature's treshold! Now it's at $temp C°."

 sendEmail -v  -f $sender -t $receiver -u object -s $smtp -xu $username -xp $pass -m $tempresult

fi
exit
